#! /bin/sh
. panel_colors
pkill panel ; pkill lemonbar ; panel &
st -c scratchterm &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width        1
bspc config window_gap		0
bspc config ignore_ewmh_struts "true"
#bspc config bottom_padding		${PANEL_HEIGHT}
bspc config top_padding		${PANEL_HEIGHT}
bspc config presel_feedback_color "${COLOR_DEFAULT_BG}"
bspc config focused_border_color "${COLOR_MAGENTA}"

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a Gimp desktop='^6'
bspc rule -a scratchterm sticky=on state=floating hidden=on rectangle=1357x200+-0+"${PANEL_HEIGHT}"
bspc rule -a ncpamixer state=floating
bspc rule -a Vieb desktop='^2'
bspc rule -a robloxplayerbeta.exe desktop='^3'
bspc rule -a Steam desktop='^3'
